[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
RingGrids = "d1845624-ad4f-453b-8ff4-a8db365bf3a7"
SpeedyWeather = "9e226e20-d153-4fed-8a5b-493def4f21a9"
SpeedyWeatherInternals = "34489162-d270-4603-8b96-37b04f830d73"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Terrarium = "80418d68-07fa-499d-ae2b-c12e531f5cd8"

[compat]
SpeedyWeatherInternals = "0.1.2"

[sources.Terrarium]
path = "../.."
